### ISSUE TITLE
[?] Supermicro X10DRU-i+

### ISSUE THREAD

**Issue by gyrene2083** [dalkain/Unraid-SuperMicro-IPMI-Auto-Fan-Control#1]
First I wanted to thank you for this script, but have a question. I have the above board, and it doesn't have a FANA or FANB it's just Fans1-8, and I have my CPU Fans on 4, 6. 

I like you couldn't get Dynamix nor IPMI Plugin working properly if at all. How would I alter your script if it only has Fans1-8?

Thanks again.

**Comment by dalkain** [comment]
Hi gyrene2083,

The board I used with this script was the X10DRi-T4+ (full disclosure -- I actually decommissioned that server as of about a month ago) and it is the only SuperMicro board I used this with. Based off my findings which led me to writing it, I don't see there being compatibility problems.

I assume that the script would still work as-is without any modifications (aside from the normal configurations listed in the first half of the file, of course) but that with only a single fan zone it would essentially only adjust the fans based off the CPU temps the way that it is written. 

One very janky way to get the drives to be a factor would be to comment out line 243 and replace line 245 with:
`new_cpu_fan_speed="$(get_max_number $found_cpu_threshold $found_disk_threshold)"`
I can't say I'd recommend this. The way the logic works, if the temperature thresholds aren't balanced the way they were for my specific system and environment there is high potential for the fans to actually _slow down_ when the CPUs are running hot (which is honestly way more likely and more potentially problematic than your drives running a little warm).

I've no doubt the logic could be rewritten to make more sense for single-fan-zone boards to allow the fan speed to increase if the drives were, but I don't really have any way of testing changes and with my limited knowledge of bash I'm not terribly comfortable just rewriting it and hoping I did everything correctly.

**Comment by gyrene2083** [comment]
I appreciate your responding, I did have to add the following to the top of the script for it to run, which is weird because I thought ipmitool would run out the box;

modprobe ipmi_si
modprobe ipmi_devintf

Then I ran the script and commented out cpus I didn't need, and ran it. It dropped from 100% to well not sure what it drops to but it's less than 50% then after a few minutes it ramps up to 100%. Any ideas on that?

**Comment by dalkain** [comment]
The only insight I can give in regards to the fans going back to 100% is that the only place in the scripts where the fans get set to 100% is when the ipmi_fans_startup.sh starts and sets "Full Speed Mode," but as explained that script should only be run a single time at the startup of your array (or if your array is already started you can run it once manually) and the ipmi_fans_auto.sh is the one that should be run on a cron schedule.

If you are only running ipmi_fans_startup once and your fans are returning to 100% a few minutes later, then there is something unrelated to these scripts that is controlling your fan settings.

It should also be noted that the speeds these scripts set are not based on the sound level, but on the fan duty cycles. Fans will typically have an exponential increase in sound as you speed them up; from what I recall from my (very unscientific and in no way actually measured) testing the 50% fan speed set by the startup script only generated around 20% of the sound.

**Comment by gyrene2083** [comment]
Thank you for the response, I continued playing around and found a simple script which seemed to work, see below, 

```
#set fan mode to "full"
ipmitool raw 0x30 0x45 0x01 0x01
#set fans in "system" zone to 32%
ipmitool raw 0x30 0x70 0x66 0x01 0x00 0x20
#set fans in "system" zone2 to 32%
ipmitool raw 0x30 0x70 0x66 0x01 0x01 0x20
```

I tested that for an hour and it worked with no issues. I then started thinking about the two zones, and someone in FreeNas said I should move the CPU over to zone 1, So I am in the process of moving CPU2 to zone 1 with CPU 1. Then I can move all the fans on to zone 2. What are your thoughts on this?

**Comment by dalkain** [comment]
I don't know what defines zone1 and zone2 for your specific board if all of your fan headers are numerical, but that is literally the exact same ipmitool commands as the ipmi_fans_startup.sh script from this repo with less descriptive comments and a lower configured duty cycle. If you only want to set one fan speed it'll do everything you want, but it's not going to adjust dynamically based on current temperatures which was the entire point of the scripts in this repo.

If you've found someone with your motherboard who is scripting things out, it may be far more worthwhile to inquire with them.

_EDIT: Just to clarify, I'm not trying to claim whoever posted that "stole" my script or anything of the sort -- those are just the commands that need to be run to set the fan speeds via ipmitool for SuperMicro boards._

**Comment by gyrene2083** [comment]
The problem is I haven't found anyone with my motherboard that has responded. lol. I did figure out that zone 1 consisted of fan headers 1-4, and zone 2 was fan headers 5-8. I honestly like your dynamic approach and really want to make that work.

So, once I'm done redoing all the fan header moving I'm going to run the script again and see how that works out and post back the results if that is ok with you.

**Comment by dalkain** [comment]
Interesting (but not surprising) that in the same generation of boards they flipped to all-numeric labels and just split them up. If you've confirmed that the two zones are set up that way and move your connections around to match, then the scripts should work perfectly to adjust your fan speeds as necessary. You'll probably still want to read through the top half of the _auto script to configure it to your liking of course.

**Comment by gyrene2083** [comment]
So here's a kicker now I run the script everything seems fine, but it stays at full speed. Here's what I see in the beginning when the script is run;
```

Script location: /tmp/user.scripts/tmpScripts/IPMI_Auto/script
Note CPU temps found: 33
Max CPU Package temp determined: 33
All CPUs are below 65 degree HOT1 temperature threshold.
Found the following potential drives: parity disk1 disk2 disk3 disk4 disk5 disk6 disk7 disk8 disk9 disk10 disk11 disk12 disk13 disk14 disk15 disk16 disk17 disk18 disk19 disk20 disk21 disk22 parity2 cache
NOTE: It is normal for this to show the max number of array disks Unraid will support. Please do not open an issue for this.
Active drive temps found: 28
Max drive temp determined: 28
All disks are all below 45 degree HOT1 temperature threshold.
```
Any ideas, and I really appreciate you taking the time to help.

**Comment by dalkain** [comment]
To confirm, did you run the ipmi_fans_startup.sh script at least one time since your server was last rebooted before running the auto script?

Did you change any of the configuration values at the top for the duty cycles? If so, can you include the new values?

Were you ever able to determine what caused your fans to go back to full speed after your second comment on this thread? If something else is changing the fan mode to anything other than Full Speed Mode (other modes may cause fans to ramp up to 100% based on whatever criteria SM has programmed into the firmware). One quick way to make sure the fans are still in Full Speed mode would be to log into the IPMI interface and check. If I recall correctly, it's under Configuration > Fan Mode or something similar.

And I'm also just recalling that there is a failsafe in place, or at least there was on my board, to protect against fan failures. If a fan gets disconnected while the server is running, it assumes the fan has failed and forces all of the remaining fans to 100%. Once a fan is reconnected to the same header I believe it will recover (or you can run the start-up script to kick it back into the controllable mode), but it may not be able to recover without a reboot if you don't reconnect all of the same headers. It was a couple years ago I last experimented with that failsafe so I may be remembering the recovery details incorrectly.

**Comment by gyrene2083** [comment]
I'm sorry it took so long to get back to you but I found a bad cable on one of the fans that just kept it at Full Speed no matter what I did. I replaced the cable, restarted the server, ran the Startup Script, which worked well. I checked SMs IPMI webpage, and although the fans were at 50% (last line of your startup file) it was indeed at FullSpeed. Then I ran the auto script and it went into Full Speed. 

I didn't change any of the values you had set, and it doesn't ramp up or down, it just goes straight into full speed mode. Thanks again for taking the time out to help.

**Comment by dalkain** [comment]
I'm sorry, but you seem to have something else interfering with fan control (either software or hardware) and it's outside of my ability to troubleshoot in this fashion and outside of the scope of this script.

Unless you changed values, which you've stated you haven't, there isn't a single line of code even commented out in the impi_fans_auto.sh file provided in this repo that could cause the fans to go back to full speed.
