### ISSUE TITLE
Unable to send RAW command

### ISSUE THREAD

**Issue by omygolly** [dalkain/Unraid-SuperMicro-IPMI-Auto-Fan-Control#2]
`ipmitool raw 0x30 0x70 0x66 0x01 0x00 0x32`

generated the following error for me in the startup-script:

'Unable to send RAW command (channel=0x0 netfn=0x30 lun=0x0 cmd=0x70 rsp=0xcc): Invalid data field in request'

I'm using a X9SCM with FAN1 FAN2 FAN3 FAN4 & FANA.

**Comment by omygolly** [comment]
Same when I run the actual fan-script:

All disks are all below 45 degree HOT1 temperature threshold.
Unable to send RAW command (channel=0x0 netfn=0x30 lun=0x0 cmd=0x70 rsp=0xcc): Invalid data field in request
Unable to send RAW command (channel=0x0 netfn=0x30 lun=0x0 cmd=0x70 rsp=0xcc): Invalid data field in request

**Comment by dalkain** [comment]
Hi @omygolly 

This script is not maintained and I am going to mark it as archived. I'm assuming that your board requires different raw commands to be sent, but I am not able to provide insight into what those might be. Everything I've found indicated that X9 used the same raw ipmi commands as X10. Once you find the proper commands, you should be able to modify the script to make them work.

Good luck!
